name: aoc-php

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            XDEBUG_MODE: debug
            PHP_IDE_CONFIG: "serverName=app"
        working_dir: /app
        command:
            - tail
            - -f
            - /dev/null
